---

- name: install required cups
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - 'cups'


## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
